name: Building

on:
    push:
        branches:
            - "development"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout
                uses: actions/checkout@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Build typescript and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./.github/workflows/typescript.Dockerfile
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/typescript_node:latest
            -
                name: Build gcc13_emsdk and push
                uses: docker/build-push-action@v4
                with:
                    context: .
                    file: ./.github/workflows/gcc13_emsdk.Dockerfile
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/gcc13_emsdk:latest